version: "3"
services:
  nodejs:
    build:
        context: C:\ProgramData\Jenkins\.jenkins\workspace\rest_server
        dockerfile: Dockerfile
    #command: "node server/server.js"
    tty: true
    restart: unless-stopped
    ports:
      - 3000:3000
  mongo:
    image: mongo:4.4-nanoserver-1809
    restart: unless-stopped
    ports:
      - 27017:27017
